#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: adapter
  group: services
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: Service
    name: adapter-issuer
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: adapter-issuer
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: adapter-issuer
- source:
    kind: Service
    name: adapter-issuer-didcomm
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    - spec.rules.0.host
    options:
      delimiter: .
    select:
      kind: Ingress
      name: adapter-issuer-didcomm
  - fieldPaths:
    - spec.rules.0.http.paths.0.backend.service.name
    select:
      kind: Ingress
      name: adapter-issuer-didcomm
- source:
    kind: Secret
    name: adapters-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: adapter-issuer
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: adapter-issuer-didcomm

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: adapters-wildcard-cert
  type: kubernetes.io/tls
- behavior: replace
  files:
  - keys/oidc-enc.key
  name: adapter-issuer-oidc-key


configMapGenerator:
- behavior: merge
  envs:
  - issuer/config.env
  name: adapter-issuer-env
- files:
  - certs/ca.crt
  name: adapter-ca-cert

resources:
- ../common
- ingress.yml

transformers:
- sedtransform.yml

patchesStrategicMerge:
- add-ca.yml
