#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: issuer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: issuer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: issuer-didcomm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: didcomm-port
  selector:
    app: issuer
status:
  loadBalancer: {}
