#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      volumes:
        - name: keys
          secret:
            secretName: auth-keys
        - name: config
          configMap:
            name: auth-config
      containers:
      - name: auth
        envFrom:
          - configMapRef:
              name: auth-env
          - secretRef:
              name: auth-env-secret
        image: hub-auth:latest
        imagePullPolicy: IfNotPresent
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
        volumeMounts:
          - name: keys
            mountPath: /etc/hub-auth/keys
            readOnly: true
          - name: config
            mountPath: /etc/hub-auth/config
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http-port
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: auth
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-port
  selector:
    app: auth
status:
  loadBalancer: {}
