#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

configMapGenerator:
- envs:
  - issuer/config.env
  name: issuer-env
- files:
  - issuer/config.json
  name: issuer-config

secretGenerator:
- envs:
  - issuer/secret.env
  name: issuer-env-secret

resources:
- issuer/deployment.yml
- issuer/service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: issuer-adapter
  newName: ghcr.io/trustbloc-cicd/issuer-adapter
  newTag: 0.1.8-snapshot-ee371c1
